### ISSUE TITLE
Using bbox during testing

### ISSUE THREAD

**Issue by LjIA26** [open-mmlab/mmpose#2005] opened 2023-02-25 19:41 UTC
Hello,

Upon testing, it seems like the algorithm is not taking the bounding boxes from the JSON file during testing because when I saved the images the bounding boxes appear all over the place. Is there a way to fix this ? 

How can I make the bounding box be the only area where the prediction happens? I am getting predictions all over the place outside the bounding box. During training, the visualization of the transforms let me know that the bounding box is where the training happens and not outside of this area. 

Thank you for your time.

**Comment by LjIA26** [comment] 2023-02-26 18:53
I am sorry if I wasn't very clear with the question, I just edited it.

**Comment by Tau-J** [comment] 2023-02-27 02:46
Hi, thanks for using MMPose. For evaluation, you can set `bbox_file` in `val_dataloader` and `test_dataset`. For prediction, you should use a detector first to provide bboxes. We provide a demo script `demo/topdown_inference_with_mmdet.py` so that you can conduct the pipeline inference.

**Comment by LjIA26** [comment] 2023-02-27 05:45
Yes, it is for evaluation of my testing set. Is the tool/test.py still in development then?

**Comment by LjIA26** [comment] 2023-02-27 05:49
```
python tools/test.py configs/plantsv5.py train-F24/epoch_50.pth --work-dir test-F24/ --show-dir test-F24/
```

```
test_dataloader =  dict(
    batch_size=10,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        metainfo=dict(from_file='configs/_base_/datasets/plantsv5.py'),
        ann_file='annotations/convertedv2.json',
        bbox_file='data/buildings/person_detection_results/bbox.json',
        data_prefix=dict(img='images-1/'),
        test_mode=True,
        pipeline=test_pipeline
    ))
```

**Comment by Tau-J** [comment] 2023-02-27 05:58
Sorry I can't reproduce the error you encountered. Would you mind providing a visualized image that `tools/test.py` saved?

**Comment by LjIA26** [comment] 2023-02-27 06:12
![image](https://user-images.githubusercontent.com/80732282/221487706-f37c6d7d-91c3-4a7c-bc7a-b9ee90a729f2.jpeg)

This is an example of the types of results I get.

The bounding box doesn't fit which comes from the ground truth file doesn't fit the whole image and the prediction is applied to the whole image. 

Also, I don't have access to my pc at the moment it's very late over here. Thank you for your comprehension.

**Comment by LjIA26** [comment] 2023-02-27 06:14
Having the prediction only inside the bounding box is very important in my case as I have two classes. One where only the prediction inside the bbox is required.

**Comment by Tau-J** [comment] 2023-02-27 06:21
In MMPose, all predicted keypoints will be inside bboxes.

**Comment by LjIA26** [comment] 2023-02-27 15:05
Yes, that's the problem. It's not working and the boxes are sized in odd shapes, very different to their ground truths. When I use the visualization tool, in transformed mode, I can see that the bbox are correct.

**Comment by Tau-J** [comment] 2023-02-27 15:27
Sorry, I can't locate the error with the information you provided, nor can I reproduce your problem on the coco dataset. Maybe when you have access to your computer you can share a real image to help me understand. 

Also, in the test phase, MMPose will directly use the bbox provided by bbox_file for prediction, and should not transform the data, so you should not use the transformed mode to check whether the bbox is correct or not.

**Comment by LjIA26** [comment] 2023-03-01 03:20
Sorry! turns out those images with the weird bboxes had the w and h inverted. Very sorry about that! 

However, there seems to be an offset for the prediction outside the bounding box, which in my case does matter. Is there a way to edit that offset? 

Again, sorry for the previous confusion.

**Comment by Tau-J** [comment] 2023-03-01 03:29
If you are using top-down heatmap, there should not be offsets, all predicted results should be inside bboxes. More specifically, the predicted coordinates are from Argmax, whose outputs must be within the bboxes.

**Comment by LjIA26** [comment] 2023-03-07 04:19
Hello, 

yes, I am using top down. Here is an example. As you can see the prediction of the keypoints is outside of the bounding box.  The bounding box in the bottom half of the prediction. 


![PIC225G79_0](https://user-images.githubusercontent.com/80732282/223319618-a332a9ce-607e-45eb-859d-25140b842c3a.png)

**Comment by LjIA26** [comment] 2023-03-09 17:34
So there is no way to solve it ? @Tau-J @ly015

**Comment by Tau-J** [comment] 2023-04-12 06:49
Sorry for late reply, I still can't reproduce your problem on the coco dataset. If you have solved it, please share me some clues.

**Closed** 2023-04-19 04:04 UTC

**Comment by LjIA26** [comment] 2023-05-01 15:39
Hello, 
I have not solved it. Sorry I haven't been able to work on my research for 2 months. But now I am back.
