### ISSUE TITLE
Higher HRNet multi-scale results on CrowdPose

### ISSUE THREAD

**Issue by CR320** [open-mmlab/mmpose#655] opened 2021-05-19 01:20 UTC
Hi,
Thank you very much for your work.
When I  do multi-scale inference  for HigherHRNetw32 on the CrowdPose test split (set test_scale_factor=[2, 1]), I find the results look different from your report. (The model is also downloaded from mmpose)

 Average Precision  (AP) @[ IoU=0.50:0.95 | type=   all | maxDets= 20 ] = 0.639
 Average Precision  (AP) @[ IoU=0.50      | type=   all | maxDets= 20 ] = 0.831
 Average Precision  (AP) @[ IoU=0.75      | type=   all | maxDets= 20 ] = 0.688
 Average Recall     (AR) @[ IoU=0.50:0.95 | type=   all | maxDets= 20 ] = 0.718
 Average Recall     (AR) @[ IoU=0.50      | type=   all | maxDets= 20 ] = 0.884
 Average Recall     (AR) @[ IoU=0.75      | type=   all | maxDets= 20 ] = 0.760
 Average Precision  (AP) @[ IoU=0.50:0.95 | type=  easy | maxDets= 20 ] = 0.702
 Average Precision  (AP) @[ IoU=0.50:0.95 | type=medium | maxDets= 20 ] = 0.646
 Average Precision  (AP) @[ IoU=0.50:0.95 | type=  hard | maxDets= 20 ] = 0.555

It is worse than single-scale test. 
I am not sure if I have done everything correct.

**Comment by jin-s13** [comment] 2021-05-19 06:27
Thanks for reporting. This is caused by the bug in the upstream lib (xtcocotools). We will fix it soon. 
For now, please use `xtcocotools==1.6` for evaluation.

**Comment by jin-s13** [comment] 2021-05-20 03:23
Fixed in `xtcocotools==1.8`.

**Closed by jin-s13** 2021-05-20 03:23 UTC
Labels: bug, upstream
