### ISSUE TITLE
Could you find the problem in my custom train process?

### ISSUE THREAD

**Issue by shinysoo** [open-mmlab/mmpose#1888] opened 2022-12-20 10:01 UTC
Hello, I'm trying to train model with my custom datasets.
so I prepared train images and annotation json files as coco style.

After that, I changed cofig file(`td-hm_hrnet-w32_8xb64-210e_coco-256x192_custom.py`) is as follows:

```
data_root = 'data_custom/coco/' 

# pipelines
train_pipeline = [
    dict(type='LoadImage', file_client_args={{_base_.file_client_args}}),
    dict(type='GetBBoxCenterScale'),
    dict(type='RandomFlip', direction='horizontal'),
    dict(type='RandomHalfBody'),
    dict(type='RandomBBoxTransform'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='GenerateTarget', encoder=codec),
    dict(type='PackPoseInputs')
]
val_pipeline = [
    dict(type='LoadImage', file_client_args={{_base_.file_client_args}}),
    dict(type='GetBBoxCenterScale'),
    dict(type='TopdownAffine', input_size=codec['input_size']),
    dict(type='PackPoseInputs')
]

# data loaders
train_dataloader = dict(
    batch_size=64,
    num_workers=2,
    persistent_workers=True,
    sampler=dict(type='DefaultSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/person_keypoints_train_custom.json', 
        data_prefix=dict(img='train_custom/'),  
        pipeline=train_pipeline,
    ))
val_dataloader = dict(
    batch_size=32,
    num_workers=2,
    persistent_workers=True,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False, round_up=False),
    dataset=dict(
        type=dataset_type,
        data_root=data_root,
        data_mode=data_mode,
        ann_file='annotations/person_keypoints_val_custom.json', 
        bbox_file='data/coco/person_detection_results/' 
        'COCO_val2017_detections_AP_H_56_person.json',  
        data_prefix=dict(img='val_custom/'),
        test_mode=True,
        pipeline=val_pipeline,
    ))
test_dataloader = val_dataloader

# evaluators
val_evaluator = dict(
    type='CocoMetric',
    ann_file=data_root + 'annotations/person_keypoints_val_custom.json')
test_evaluator = val_evaluator
```

And the demo script is as follows:

```
!python demo/topdown_demo_with_mmdet.py \
    demo/mmdetection_cfg/faster_rcnn_r50_fpn_coco.py \
    https://download.openmmlab.com/mmdetection/v2.0/faster_rcnn/faster_rcnn_r50_fpn_1x_coco/faster_rcnn_r50_fpn_1x_coco_20200130-047c8118.pth \
    configs/body_2d_keypoint/topdown_heatmap/coco/td-hm_hrnet-w32_8xb64-210e_coco-256x192_custom.py \
    https://download.openmmlab.com/mmpose/top_down/hrnet/hrnet_w32_coco_256x192-c78dce93_20200708.pth \
    --input /pose_estimation/_sample_data/20210719_160714_color.mp4 \
    --output-root=output/base \
    --device=cuda:0 \
    --show --save-predictions 
```

Right, I've only modified the paths of annotations and images in the config file.
And I compared "origin predictions result" and "custom-train predictions result".

As expected, there was no difference between "origin predictions result" and "custom-train predictions result".
I think the custom config didn't work and the origin config file worked twice.

What's the problem in the process?
Should I change this code?:
```
bbox_file='data/coco/person_detection_results/' 
	'COCO_val2017_detections_AP_H_56_person.json'
```

or should I modify the `{MMDET_CONFIG_FILE}` and `{~_CHECKPOINT_FILE}` in the demo script?

Please find the poblems in my code.
Thank you.

**Comment by Tau-J** [comment] 2022-12-20 10:11
Thanks for using MMPose 1.0. For custom dataset, you should not use `COCO_val2017_detections_AP_H_56_person.json`, which contains bboxes detected by a detector on COCO dataset.

**Comment by shinysoo** [comment] 2022-12-20 12:14
> `COCO_val2017_detections_AP_H_56_person.json`, whic

Can you share the format of `COCO_val2017_detections_AP_H_56_person.json`?

**Comment by shinysoo** [comment] 2022-12-21 01:51
> 

I found the json from this [Google Drive](https://drive.google.com/drive/folders/1fRUDNUDxe9fjqcRZ2bnF_TKMlO0nB_dk). Thanks!
But I have one question. How to calculate the `score`?
I have only `bbox, image_id, category_id` without `score`.

**Comment by Tau-J** [comment] 2022-12-21 04:50
`bbox_file` is not necessary for custom dataset, you can just comment it out. Then the evaluation result will be based on your GT.

**Comment by jin-s13** [comment] 2022-12-29 07:16
It seems the problem is solved. I will close this issue for now. Feel free to reopen it if have further questions.

**Closed by jin-s13** 2022-12-29 07:16 UTC
